name: "Github + WordPress Plugin Support"
description: "Integrate github to handle wordpress plugin support."
inputs:
  plugin-slug:
    description: "Plugin Slug"
    required: true
  github-token:
    description: "Github Token"
    required: true
outputs:
  time:
    description: "The time we greeted you"
runs:
  using: "node12"
  main: "index.js"
